
services:
  app:
    image: development.cr.cloud.ru/portfolio:v2
    build:
      args:
        - SMTP_PASS=${SMTP_PASS}
        - SMTP_USER=${SMTP_USER}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - MAIL_LOCALE==${MAIL_LOCALE}
        - PAYLOAD_SECRET==${PAYLOAD_SECRET}
      dockerfile: Dockerfile
      secrets:
        - PAYLOAD_SECRET
        - SMTP_PASS
    environment:
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_USER=${SMTP_USER}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - MAIL_LOCALE==${MAIL_LOCALE}
      - PAYLOAD_SECRET==${PAYLOAD_SECRET}
    restart: unless-stopped
    volumes:
      - ./db:/app/db
      - ./public/media:/app/public/media
    ports:
      - 3000:3000

secrets:
  PAYLOAD_SECRET:
    environment: PAYLOAD_SECRET
  SMTP_PASS:
    environment: SMTP_PASS
