
services:
  app:
    image: development.cr.cloud.ru/portfolio:v1
    build:
      args:
        - URL=${URL}
        - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      dockerfile: Dockerfile
    container_name: portfolio
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
