version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - URL=${URL}
    restart: unless-stopped
    container_name: portfolio
    ports:
      - '${PORT:-3000}:3000'
    environment:
      URL: ${URL}
      RESEND_KEY: ${RESEND_KEY}
      RESEND_TO: ${RESEND_TO}
      MAIL_LOCALE: ${MAIL_LOCALE}
      GITHUB_REPO: ${GITHUB_REPO}
    env_file:
      - .env
    volumes:
      - ./public/content:/app/public/content
